#!/bin/bash -x 

LIB="$(dirname ${BASH_SOURCE[0]})"/lib.sh
if [ ! -e $LIB ] 
then 
	echo "ERROR: Required file not found: $LIB" >&2
	exit 1
else
	source $LIB
fi

DATESTAMP=$(date +%Y%m%d%H%M)
BASEDIR=$(basedir)
LIVEDIR=$BASEDIR/Livecd-root
ISODIR=$BASEDIR/Completed

function mkiso() {
	[ -e $ISODIR ] || mkdir $ISODIR || fail

	# Recalc md5sums
	pushd $LIVEDIR ||  fail
	rm md5sum.txt ;	find -type f -print0 | xargs -0 md5sum | grep -v isolinux/boot.cat | tee md5sum.txt 
	popd 

	pushd $LIVEDIR ||  fail
	mkisofs -m '.fuse_*' -D -r -V "Tunapanda-$DATESTAMP" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $ISODIR/tunapanda-${DATESTAMP}.iso . ||  fail
	popd 
}

$BASEDIR/Scripts/env_setup.sh || fail
pushd $BASEDIR || fail
echo "DVD version $DATESTAMP" > $LIVEDIR/tunapanda/VERSION.txt
mkiso || fail
popd
